[profile.default]
solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]


remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[optimizer]
enabled = false
runs = 200 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
